import { useState } from "react";
import { Layout } from "@/components/layout";
import { SEO } from "@/components/seo";
import { Link } from "wouter";
import { ArrowRight, ArrowUpRight, Plus, MoveUpRight } from "lucide-react";
import { headshot, portfolioImages } from "@/lib/images";
import { publicPath } from "@/lib/paths";

const phases = [
  { label: "Find the signal", words: ["SEARCH", "INTENT"], body: "Understand what people need, where they look, and what’s missing.", nodes: ["Query", "Context", "Opportunity"] },
  { label: "Build the system", words: ["CONNECT", "THE DOTS"], body: "Turn the opportunity into useful pages, products, and repeatable workflows.", nodes: ["Entities", "Content", "Experience"] },
  { label: "Measure the change", words: ["PROVE", "PROGRESS"], body: "Connect the work to observable outcomes. Learn, refine, and repeat.", nodes: ["Baseline", "Outcome", "Next move"] },
];
function SignalCanvas(){const [active,setActive]=useState(0);const p=phases[active];return <div className="signal-canvas"><div className="canvas-top"><span>THE WAY I WORK</span><span>0{active+1} / 03</span></div><div className="signal-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="signal-type">{p.words.map(w=><span key={w}>{w}</span>)}</div><span className="canvas-node node-one">{p.nodes[0]}</span><span className="canvas-node node-two">{p.nodes[1]}</span><span className="canvas-node node-three">{p.nodes[2]}</span><Plus className="crosshair crosshair-one"/><Plus className="crosshair crosshair-two"/></div><div className="canvas-caption" aria-live="polite"><span className="signal-dot"/><p>{p.body}</p></div><div className="canvas-controls" aria-label="Explore the working process">{phases.map((phase,i)=><button key={phase.label} aria-pressed={i===active} onClick={()=>setActive(i)}><span>0{i+1}</span>{phase.label}</button>)}</div></div>}

export default function Home(){return <Layout><SEO title="Mitchell Miller — Search, AI & Growth Systems" description="Enterprise search leadership meets hands-on AI and growth engineering. Explore Mitchell Miller’s work at Apple, CommonSpirit, Stanford Health Care and SFC Surf School."/>
  <section className="site-wrap home-hero"><div className="hero-copy"><p className="eyebrow"><span className="tiny-dot"/> ENTERPRISE EXPERIENCE. BUILDER’S INSTINCT.</p><h1>I turn search<br/>opportunities into<br/><em>things that work.</em></h1><p className="hero-deck">I’m Mitch. I connect search strategy, useful content, and practical AI to build systems that help businesses grow.</p><div className="hero-actions"><Link href="/case-studies" className="button-ink">Explore the work <ArrowUpRight size={19}/></Link><Link href="/lab" className="text-link">Try the interactive lab <ArrowRight size={17}/></Link></div><div className="hero-person"><img src={headshot} width="46" height="46" alt="Mitchell Miller"/><p>MITCHELL MILLER<span>Search leader. Product thinker. Hands-on builder.</span></p></div></div><SignalCanvas/></section>
  <div className="experience-strip"><div className="site-wrap"><span className="eyebrow">EXPERIENCE ACROSS</span><p>Apple</p><p>Stanford Health Care</p><p>CommonSpirit</p><p>Clarity AI</p><p>SFC Surf School</p></div></div>
  <section className="site-wrap portfolio-section"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Big systems.<br/><em>Real-world outcomes.</em></h2></div><p>From a thousand healthcare locations to a surf school in Waikīkī. Different scales, the same commitment to making things work.</p></div>
    <Link href="/case-studies/sfc-surf-school" className="feature-project"><div className="feature-project-image"><img src={publicPath('/images/portfolio-proof/sfc-south-shore-explorer.png')} alt="SFC Surf School’s interactive South Shore surf-break explorer" loading="lazy"/><span className="image-tag">EXPLORE THE LIVE WORK <ArrowUpRight size={16}/></span></div><div className="feature-project-copy"><p className="eyebrow">SFC SURF SCHOOL / 2026</p><h3>A local business.<br/>A bigger digital possibility.</h3><p>Search-led content, a custom interactive surf map, and a repeatable way to turn local expertise into a useful customer experience.</p><div className="feature-result"><strong>5 → 54</strong><span>Google Search clicks<br/>in consecutive 28-day periods</span></div><p className="micro-note">Aug 12–Sep 8 vs. Jul 15–Aug 11, 2026.<br/>Early growth preceding the Sep 10 map launch.</p><span className="text-link">Inside the SFC project <ArrowUpRight size={18}/></span></div></Link>
    <div className="project-pair"><Link href="/case-studies/commonspirit-locations-conversion-engine" className="editorial-project"><div className="architecture-visual" aria-label="One connected location system, more than 1,000 pages"><span>ONE CONNECTED FOUNDATION</span><div className="architecture-nodes"><i/><i/><i/><strong>1,000+</strong><i/><i/><i/></div><span>ENTITIES → PAGES → PATIENT ACTIONS</span></div><div className="project-meta"><p>COMMONSPIRIT / DIGNITY HEALTH</p><ArrowUpRight/></div><h3>Making a healthcare network<br/>easier to find. And act on.</h3><p>Location architecture connected to $15.21M in FY22 attributable revenue.</p></Link><Link href="/case-studies/apple-seasonal-search" className="editorial-project"><div className="editorial-project-image"><img src={portfolioImages['apple-seasonal-search'].src} alt={portfolioImages['apple-seasonal-search'].alt} loading="lazy"/></div><div className="project-meta"><p>APPLE / AMERICAS</p><ArrowUpRight/></div><h3>Search strategy at<br/>enterprise scale.</h3><p>Seasonal commerce, international architecture, and the alignment that gets technical work prioritized.</p></Link></div>
    <div className="section-end"><Link href="/case-studies" className="text-link">All case studies <ArrowRight size={18}/></Link></div>
  </section>
  <section className="lab-feature"><div className="site-wrap lab-feature-grid"><div><p className="eyebrow">02 / THE INTERACTIVE LAB</p><h2>Don’t just read<br/>about the thinking.<br/><em>Play with it.</em></h2><p>Change the inputs. Follow the connections. See how I turn a question into a system you can use.</p><Link href="/lab" className="button-paper">Open the lab <ArrowUpRight size={18}/></Link></div><div className="lab-menu">{[{n:'01',title:'Where intent becomes opportunity',detail:'A place + an activity. Explore what the query tells us.',hash:'intent'},{n:'02',title:'The story behind a growth number',detail:'Compare the counts. Understand the change.',hash:'evidence'},{n:'03',title:'A system that scales with you',detail:'Connect entities, content, experience, and measurement.',hash:'architecture'}].map(i=><Link key={i.n} href={`/lab#${i.hash}`} className="lab-menu-item"><span>{i.n}</span><div><h3>{i.title}</h3><p>{i.detail}</p></div><MoveUpRight/></Link>)}</div></div></section>
  <section className="site-wrap portfolio-section"><div className="section-heading"><div><p className="eyebrow">03 / HOW I CAN HELP</p><h2>Strategy is the start.<br/><em>Delivery makes it matter.</em></h2></div><Link href="/collab-ideas" className="text-link">Ways to work together <ArrowRight size={18}/></Link></div><div className="capability-grid">{[{n:'01',title:'Search & discovery',body:'Find the valuable gaps across organic search, local discovery, and AI-generated answers.',link:'/aeo-geo',cta:'Explore my search approach'},{n:'02',title:'Content & growth systems',body:'Build the entity models, page templates, and measurement that make useful content scale.',link:'/systems',cta:'See how the system connects'},{n:'03',title:'Applied AI & useful tools',body:'Turn reporting, research, and operational friction into working tools your team can use.',link:'/selected-builds',cta:'Explore the builds'}].map(i=><article key={i.n}><span className="capability-number">{i.n}</span><h3>{i.title}</h3><p>{i.body}</p><Link href={i.link} className="text-link">{i.cta}<ArrowUpRight size={17}/></Link></article>)}</div></section>
  <section className="site-wrap about-band"><img src={headshot} width="240" height="240" loading="lazy" alt="Mitch Miller"/><div><p className="eyebrow">A LITTLE ABOUT ME</p><h2>Curiosity is the through line.</h2><p>I’ve worked inside global brands, healthcare networks, agencies, and small businesses. The work changes. The instinct stays the same: understand the problem deeply, then make something useful.</p><Link href="/about" className="text-link">The longer story <ArrowUpRight size={18}/></Link></div><Link href="/resume" className="resume-aside"><span>HIRING?</span><strong>Get the<br/>full picture.</strong><span>Updated resumes <ArrowUpRight size={16}/></span></Link></section>
</Layout>}
