// Flattens the production agency shell stylesheet into the design-system entry
// stylesheet, so the uploaded bundle has no relative @import outside its own tree.
//
// The shim goes BEFORE the shell: the shell styles <body class="ag-body"> and the
// design system applies the same base to a wrapper <div>, but shim rules that land
// after the shell win specificity ties and break later overrides (e.g. the white
// heading inside .ag-hero).
import { readFileSync, writeFileSync } from 'node:fs';

const shell = readFileSync('site/styles/agency.css', 'utf8');
const header = `/* M2 agency design system entry stylesheet - GENERATED by scripts/build-ds-css.mjs.
   Source of truth: site/styles/agency.css. Edit that file, not this one. */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

/* Shim: base that the shell applies to <body>, applied to a wrapper element instead. */
.ag-body{margin:0;background:#fff;color:var(--ag-text);font-family:var(--ag-font);font-size:17px;line-height:1.65;-webkit-font-smoothing:antialiased}
.ag-body p{margin:0}

`;
writeFileSync('src/ds/ds.css', header + shell);
console.log('wrote src/ds/ds.css');
